ALTER TABLE dish ADD parent_id INT DEFAULT NULL, CHANGE dish_type_id dish_type_id INT DEFAULT NULL, CHANGE price price DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE dish ADD CONSTRAINT FK_957D8CB8727ACA70 FOREIGN KEY (parent_id) REFERENCES dish (id);
CREATE INDEX IDX_957D8CB8727ACA70 ON dish (parent_id);