imports:
    - { resource: security.yml }
    - { resource: sonata.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: liip_imagine.yml }
    - { resource: hwi_oauth.yml }
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    default_locale:  "%locale%"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'VichUploaderBundle:Form:fields.html.twig'
            - 'ApplicationMainBundle:Common:forms.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                mappings:
                    ApplicationMainBundle: ~
                    ApplicationPageBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\MainBundle\Entity\User
    registration:
        form:
            type: application_main_user_registration
    profile:
        form:
            type: application_main_user_profile

vich_uploader:
    db_driver:  orm
    twig: true
    mappings:
        project_response_file:
            uri_prefix:         /uploads/users
            upload_destination: %kernel.root_dir%/../web/uploads/users
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        restaurant_menu_file:
            uri_prefix:         /uploads/menu
            upload_destination: %kernel.root_dir%/../web/uploads/menu
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        dish_photo:
            uri_prefix:         /uploads/dish
            upload_destination: %kernel.root_dir%/../web/uploads/dish
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

ewz_recaptcha:
    public_key:   6Lcn2_gSAAAAADTIWqTFAmKp6PjQGmynjqVKXIdB # keys for localhost
    private_key:  6Lcn2_gSAAAAAMRZKbruKHt320-AQqMtsf0dkFQz
    locale_key:   %kernel.default_locale%
    enabled:      true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
