# # Customization of fos_user_security_login
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    pattern: /se-connecter
    defaults:  { _controller: TEMainBundle:Security:login }

fos_user_security_check:
    pattern: /se-connecter-verification
    defaults:  { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

fos_user_security_logout:
    pattern: /se-deconnecter
    defaults:  { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /mon-profil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /s-inscrire

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reinitialisation

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /mon-profil

te_main:
    resource: "@TEMainBundle/Controller/"
    type:     annotation
    prefix:   /

# admin_login route defined in TE\Bundle\MainBundle\Controller\AdminSecurityController.php
admin_login_check:
    pattern:   /_administration/login_check

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /_administration

admin_logout:
    pattern: /_administration/logout

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /_administration

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# always on end
te_page:
    resource: "@TEPageBundle/Controller/"
    type:     annotation
    prefix:   /
