fos_user_security_login:
    pattern: /login
    defaults:  { _controller: ApplicationMainBundle:Security:login }

fos_user_security_check:
    pattern: /login-verification
    defaults:  { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

fos_user_security_logout:
    pattern: /logout
    defaults:  { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /my-profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /sign-in

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset-password

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /my-profile




#HWIOAuthBundle routes
#hwi_oauth_security:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

#google_login:
#    pattern: /login/check-google





_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

application_main:
    resource: "@ApplicationMainBundle/Controller/"
    type:     annotation
    prefix:   /

# admin_login route defined in Application\MainBundle\Controller\AdminSecurityController.php
admin_login_check:
    pattern:   /_administration/login_check

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /_administration

admin_logout:
    pattern: /_administration/logout

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /_administration

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media




# always on end
application_page:
    resource: "@ApplicationPageBundle/Controller/"
    type:     annotation
    prefix:   /
