security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    richard:  { password: '1980#gtm', roles: ['ROLE_SONATA_ADMIN', 'ROLE_SUPER_ADMIN'] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        administration:
            pattern:   ^/_administration/
            provider: in_memory
            anonymous: ~
            form_login:
                login_path:  /_administration/login
                check_path:  /_administration/login_check
            logout:
                path:   /_administration/logout
                target: /

        main:
            pattern: ^/
            form_login:
                login_path:  /login
                check_path:  /login-verification
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /login-end
                use_referer: true
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-verification, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sign-in, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_administration/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_administration/, role: ROLE_SUPER_ADMIN }
