services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    my_user_provider:
        class: Application\MainBundle\Provider\FOSUBUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]
#        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]